export const SAFE_ZONE = {
  top: 96,
  bottom: 96,
  innerTop: 108,
  innerBottom: 804,
};

export const pageSpecs = [
  {
    id: "page-01",
    role: "cover",
    density: "medium",
    emphasis: "title",
    preferredLayouts: ["hero-cover", "editorial-thesis"],
    blocks: [
      { kind: "eyebrow", text: "GENERIC DECK TEMPLATE" },
      { kind: "title", text: "通用演示模板" },
      { kind: "subtitle", text: "10 页结构 · 10 套风格 · 可直接替换内容" },
      {
        kind: "summary",
        text: "这套案例不绑定具体主题，只展示同一组通用页面骨架在不同风格与版式语言中的呈现方式。",
      },
    ],
    metaLabel: "Cover",
    yearRange: "10 SLIDES",
    notes: [
      { label: "用途", text: "用于策略、项目、品牌、研究和通用汇报类 deck 的起始模板。" },
      { label: "结构", text: "覆盖开场、背景、对比、指标、判断、流程与收尾等常见页面类型。" },
      { label: "方式", text: "保留同一内容骨架，只改变 style family 与 layout prototype。" },
    ],
  },
  {
    id: "page-02",
    role: "chronology",
    density: "medium",
    emphasis: "chronology",
    preferredLayouts: ["offset-timeline", "story-rail"],
    blocks: [
      { kind: "eyebrow", text: "DECK FLOW" },
      { kind: "title", text: "标准节奏：从开场到结论" },
      {
        kind: "summary",
        text: "一套常见演示通常从 framing 开始，再进入背景、判断、证据、行动和收束。",
      },
    ],
    metaLabel: "Flow",
    footer: "无论具体主题是什么，稳定的页面节奏都会先于装饰风格决定整体可读性。",
    events: [
      { date: "01", title: "开场", text: "先建立主题、范围与阅读预期，让观众知道这套 deck 在回答什么。" },
      { date: "02-04", title: "背景与问题", text: "补充上下文、现状与约束，为后续判断提供基础。" },
      { date: "05-08", title: "判断与证据", text: "把核心论点、关键数字、对比和流程组织成清晰结构。" },
      { date: "09-10", title: "收束与行动", text: "回到结论、建议和下一步，形成完整闭环。" },
    ],
  },
  {
    id: "page-03",
    role: "comparison",
    density: "medium",
    emphasis: "contrast",
    preferredLayouts: ["comparison-bands", "ledger-columns"],
    blocks: [
      { kind: "eyebrow", text: "INPUT SHAPES" },
      { kind: "title", text: "常见输入方式：摘要型 vs 模块型" },
      {
        kind: "summary",
        text: "同一页素材通常以概览摘要或模块分栏进入系统，版式需要据此重组，而不是照抄文档结构。",
      },
    ],
    metaLabel: "Inputs",
    columns: [
      {
        heading: "摘要型输入",
        points: [
          "适合概览、结论、背景页。",
          "通常以短段落和 3 到 4 个关键点出现。",
          "重点是让观众快速获得主线，不必逐句阅读。",
        ],
      },
      {
        heading: "模块型输入",
        points: [
          "适合对比、结构拆解和角色分工。",
          "更适合转成左右栏、卡片组或条带式布局。",
          "需要先判断层级，再决定哪些信息并列、哪些信息从属。",
        ],
      },
      {
        heading: "演示化处理",
        points: [
          "不保留文档式堆叠。",
          "优先做焦点、节奏和留白。",
          "让每页只承担一个清晰阅读动作。",
        ],
      },
    ],
    footer: "模板不是固定摆法，而是帮助模型识别输入结构与输出版式之间的关系。",
  },
  {
    id: "page-04",
    role: "metric",
    density: "medium",
    emphasis: "metric",
    preferredLayouts: ["metric-commentary", "evidence-quote"],
    blocks: [
      { kind: "eyebrow", text: "SIGNAL PAGE" },
      { kind: "title", text: "关键数字页只强调一个主信号" },
      {
        kind: "summary",
        text: "当一页存在单一关键指标时，版式应该让数字先被看到，再承接解释与支撑，而不是把所有数据同时铺开。",
      },
    ],
    metaLabel: "Metric",
    metric: { value: "1", label: "Primary Signal", note: "每页只保留一个主数字" },
    bullets: [
      "把主数字作为视觉锚点，其余信息只服务解释，不与之竞争。",
      "二级信息通常用短句、标签或 3 到 4 条支撑点承接。",
      "如果同一页有太多数字，应拆页或重构，而不是缩小字号。",
      "这类页面适合在整套 deck 中承担记忆点，而不是信息堆栈。",
    ],
  },
  {
    id: "page-05",
    role: "thesis",
    density: "medium",
    emphasis: "takeaway",
    preferredLayouts: ["editorial-thesis", "ledger-columns"],
    blocks: [
      { kind: "eyebrow", text: "CORE ARGUMENT" },
      { kind: "title", text: "核心判断页需要一句可复述的结论" },
      {
        kind: "summary",
        text: "这类页面不是堆事实，而是把一组信息压缩成一个明确、可转述、可支持的判断。",
      },
    ],
    metaLabel: "Thesis",
    thesis: "先给判断，再给解释，最后给支撑。",
    accentFigure: "3 PARTS",
    commentary: [
      { label: "判断", text: "观众应先看到一句完整结论，而不是自己从碎片中拼出结论。" },
      { label: "解释", text: "用一段 lead copy 说明这句判断为什么成立、适用于什么范围。" },
      { label: "支撑", text: "再用 2 到 3 个标签化条目补充证据、限制与行动方向。" },
    ],
    footer: "判断页的任务是降低理解成本，而不是增加阅读负担。",
  },
  {
    id: "page-06",
    role: "synthesis",
    density: "medium",
    emphasis: "contrast",
    preferredLayouts: ["card-constellation", "story-rail"],
    blocks: [
      { kind: "eyebrow", text: "MIXED MODULES" },
      { kind: "title", text: "同一页可以容纳多种信息块" },
      {
        kind: "summary",
        text: "当内容不是线性叙事时，可以把标签、短句、卡片和说明组合成结构化拼贴，但层级仍然必须清楚。",
      },
    ],
    metaLabel: "Synthesis",
    cards: [
      { tag: "Tag", title: "短标签", text: "适合放置分类、状态、阶段或轻量语义标记。" },
      { tag: "Title", title: "块标题", text: "每张卡片都应有一句明确标题，让观众知道它回答什么。" },
      { tag: "Text", title: "短说明", text: "正文控制在 1 到 3 行，避免卡片变成长段文档。" },
      { tag: "Mix", title: "组合关系", text: "卡片之间可以并列，也可以形成轻度主次，但不要失去整体节奏。" },
    ],
    footer: "这类页面适合承接多点信息，但不适合容纳冗长段落。",
  },
  {
    id: "page-07",
    role: "comparison",
    density: "medium",
    emphasis: "process",
    preferredLayouts: ["process-ribbon", "comparison-bands"],
    blocks: [
      { kind: "eyebrow", text: "BUILD PROCESS" },
      { kind: "title", text: "推荐流程：读取、判断、编排、审查" },
      {
        kind: "summary",
        text: "模板类 deck 的稳定性来自清晰流程，而不是随机摆放内容或过早堆叠视觉装饰。",
      },
    ],
    metaLabel: "Process",
    steps: [
      { tag: "Step 1", title: "读取输入", text: "先把原始 Markdown 理解为页面单位，而不是逐条渲染成文档。" },
      { tag: "Step 2", title: "判断角色", text: "识别这一页是 cover、comparison、metric 还是 closing。" },
      { tag: "Step 3", title: "选择版式", text: "根据 style family 和页面角色选择更合适的 layout prototype。" },
      { tag: "Step 4", title: "审查修正", text: "检查 safe zone、层级、碰撞与可读性，再决定是否交付。" },
      { tag: "Step 5", title: "统一风格", text: "让同一套 deck 在一个 style family 内保持视觉连续性。" },
      { tag: "Step 6", title: "按需导出", text: "确认 HTML 通过审查后，再进入 PNG 与 PPTX 导出链路。" },
    ],
    footer: "流程的目的是提高一致性，同时保留足够的版式变化空间。",
  },
  {
    id: "page-08",
    role: "chronology",
    density: "medium",
    emphasis: "takeaway",
    preferredLayouts: ["story-rail", "evidence-quote"],
    blocks: [
      { kind: "eyebrow", text: "REVIEW PRIORITY" },
      { kind: "title", text: "审查优先级：先看边界，再看风格" },
      {
        kind: "summary",
        text: "先确认边界、字号与阅读顺序，再讨论风格是否成立。",
      },
    ],
    metaLabel: "Review",
    railTitle: "4",
    railSubtitle: "检查层级",
    railNote: "先解决几何问题，再打磨视觉细节",
    railItems: [
      { label: "Safe Zone", text: "所有主内容必须留在 `.main-frame` 内。" },
      { label: "Type", text: "标题与正文要有清晰字号梯度。" },
      { label: "Density", text: "一页只承担一个主要阅读动作。" },
    ],
    footer: "先修结构，再修气质。",
  },
  {
    id: "page-09",
    role: "chronology",
    density: "medium",
    emphasis: "chronology",
    preferredLayouts: ["chronology-matrix", "offset-timeline"],
    blocks: [
      { kind: "eyebrow", text: "PAGE TYPES" },
      { kind: "title", text: "常见页面类型矩阵" },
      {
        kind: "summary",
        text: "通用 deck 并不需要很多奇怪页面，覆盖几类常见角色，就能支撑大多数汇报和提案场景。",
      },
    ],
    metaLabel: "Matrix",
    cells: [
      { date: "Cover", title: "开场页", text: "负责建立主题、气质、范围和第一眼注意力。" },
      { date: "Compare", title: "对比页", text: "负责呈现差异、选项、结构或模块关系。" },
      { date: "Metric", title: "数字页", text: "负责突出一个主信号，再补支撑说明。" },
      { date: "Closing", title: "收尾页", text: "负责总结、确认下一步和稳定落点。" },
      { date: "Context", title: "背景页", text: "负责交代现状、范围、约束和问题边界。" },
      { date: "Thesis", title: "判断页", text: "负责给出一句可复述的中心结论。" },
      { date: "Process", title: "流程页", text: "负责把步骤、节奏和执行顺序组织清楚。" },
      { date: "Synthesis", title: "组合页", text: "负责承接多块信息，但仍维持清晰层级。" },
    ],
    footer: "页面类型少而清楚，往往比页面样式多而混乱更有效。",
  },
  {
    id: "page-10",
    role: "closing",
    density: "medium",
    emphasis: "takeaway",
    preferredLayouts: ["manifesto-wall", "ledger-columns"],
    blocks: [
      { kind: "eyebrow", text: "FINAL CHECK" },
      { kind: "title", text: "交付前确认：清楚、稳定、可展示" },
      {
        kind: "summary",
        text: "一套模板的价值，不是生成很多页面，而是帮助模型稳定地产出清楚、可展示、可复用的 slide 结构。",
      },
    ],
    metaLabel: "Closing",
    pillars: [
      { title: "清楚", text: "观众能在几秒内看懂每页焦点，不需要先解码布局。" },
      { title: "稳定", text: "safe zone、字号、留白和层级在不同风格下都保持可控。" },
      { title: "可展示", text: "最终结果适合投影、适合讲述，也适合继续替换为真实业务内容。" },
      { title: "可扩展", text: "同一套骨架既能用于 5 页 deck，也能扩到更完整的 10 页结构。" },
      { title: "可替换", text: "模板内容可以快速替换成业务、品牌、产品或研究主题。" },
      { title: "可复用", text: "完成一套后，后续项目只需要换内容与风格，不必重建逻辑。" },
    ],
    footer: "这套案例展示的不是一个主题，而是一种可复用的 presentation skeleton。",
  },
];
